### ISSUE TITLE
Small bug for decimal amounts of a certain item in Data tab

### ISSUE THREAD

**Issue by DatHaker123** [Joshimello/AL2Lab#2]
I'm using 1x Nuclear Core here with default settings

![image](https://github.com/Joshimello/AL2Lab/assets/128323804/2ebd49da-ff94-4c34-8e74-be0531de935e)

The number of starters do not add up to the right number. Alternatively, with 2x Nuclear Core, same settings, 

![image](https://github.com/Joshimello/AL2Lab/assets/128323804/14d3df32-8196-46f1-abff-3ff7cf211ba9)

Things add up. 

I tried with a few other random things and the same thing happens. 

I'm gonna go ahead and guess it has something to do with Math.ceil() in src/routes/al2/stores.ts

**Comment by Joshimello** [comment]
Yeap, its due to the Math.ceil I added,
my original thought was, since machines can only select one type output,
e.g. 1.5 gold, 1.5 copper, I'd need 2 starters for gold and 2 starters for copper, instead of having a starter share the 0.5 gold with the 0.5 copper.
But does it make it more complicated? Maybe add bracket number for ceiled number?
e.g. 177.5 (178) Copper

**Comment by Joshimello** [comment]
made a preview https://al2lab-git-test-joshimello.vercel.app?_vercel_share=WSmAK31Fv2nIe2wenRynaD486Hvob7UL

**Comment by DatHaker123** [comment]
I completely understand reasoning for applying ceiling, I'd have done the same. However, per the first picture, rounding up,

194 +309 + 178 + 15 + 8 = 704, not 708 as displayed

**Comment by Joshimello** [comment]
Ah! Understood the issue, my bad haha.
Fixed d3af475
